version: "3"

services:
  database:
    image: mysql:5.7.23
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: outboxmvp
      MYSQL_USER: app
      MYSQL_PASSWORD: 12345
    ports:
      - 3308:3306

  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
      - RABBITMQ_DEFAULT_VHOST=vhost
    ports:
      - "5673:5672"
      - "15673:15672"